CREATE table farmacias( 
              IdFarmacia INTEGER PRIMARY KEY AUTOINCREMENT
            , Descripcion TEXT NOT NULL UNIQUE
            , Sucursales INTEGER NOT NULL
            );

INSERT INTO farmacias (Descripcion, Sucursales)
VALUES
('FARMACIA SAN JOSE', 5),
('FARMACIA SANTA MARIA', 3),
('FARMACIA NUEVA ESPERANZA', 7),
('FARMACIA CRISTAL', 2),
('FARMACIA EL SOL', 4),
('FARMACIA LA VIDA', 6),
('FARMACIA POPULAR', 1),
('FARMACIA SANTA LUCIA', 3),
('FARMACIA SAN PABLO', 4),
('FARMACIA SANTO DOMINGO', 2),
('FARMACIA LA SALUD', 5),
('FARMACIA LA ESPERANZA', 6),
('FARMACIA MODERNA', 3),
('FARMACIA CRUZ VERDE', 4),
('FARMACIA EL ROSARIO', 2),
('FARMACIA SANTA RITA', 5),
('FARMACIA SAN MIGUEL', 6),
('FARMACIA LA FE', 3),
('FARMACIA SANTA CRUZ', 4),
('FARMACIA SAN JUAN', 2);